package com.kdelehoi.marshrutky.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Запасна палітра для Android 8–11, де динамічних кольорів із шпалер ще немає. Згенерована
 * стандартним алгоритмом Material (tonal spot) від кобальту #2453C7 — того самого, що в адаптивній
 * іконці, щоб на старих пристроях застосунок не виглядав чужим сам собі.
 */
internal val LightColors = lightColorScheme(
    primary = Color(0xFF4F5D8C),
    onPrimary = Color(0xFFFAF8FF),
    primaryContainer = Color(0xFFB7C5FA),
    onPrimaryContainer = Color(0xFF303E6A),
    inversePrimary = Color(0xFFB7C5FA),
    secondary = Color(0xFF595E72),
    onSecondary = Color(0xFFFAF8FF),
    secondaryContainer = Color(0xFFDDE1F9),
    onSecondaryContainer = Color(0xFF4C5164),
    tertiary = Color(0xFF6D567E),
    onTertiary = Color(0xFFFFF6FE),
    tertiaryContainer = Color(0xFFEDCFFF),
    onTertiaryContainer = Color(0xFF5A446B),
    background = Color(0xFFFAF8FE),
    onBackground = Color(0xFF30323B),
    surface = Color(0xFFFAF8FE),
    onSurface = Color(0xFF30323B),
    surfaceVariant = Color(0xFFE2E1ED),
    onSurfaceVariant = Color(0xFF5D5E68),
    surfaceTint = Color(0xFF4F5D8C),
    inverseSurface = Color(0xFF0D0E12),
    inverseOnSurface = Color(0xFF9D9CA2),
    error = Color(0xFFA8364B),
    onError = Color(0xFFFFF7F7),
    errorContainer = Color(0xFFF97386),
    onErrorContainer = Color(0xFF6E0523),
    outline = Color(0xFF797A84),
    outlineVariant = Color(0xFFB1B1BC),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFAF8FE),
    surfaceDim = Color(0xFFD9D9E4),
    surfaceContainer = Color(0xFFEEEDF6),
    surfaceContainerHigh = Color(0xFFE8E7F1),
    surfaceContainerHighest = Color(0xFFE2E1ED),
    surfaceContainerLow = Color(0xFFF4F3FA),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    primaryFixed = Color(0xFFB7C5FA),
    primaryFixedDim = Color(0xFFA9B7EB),
    onPrimaryFixed = Color(0xFF1B2A55),
    onPrimaryFixedVariant = Color(0xFF394774),
    secondaryFixed = Color(0xFFDDE1F9),
    secondaryFixedDim = Color(0xFFCFD3EB),
    onSecondaryFixed = Color(0xFF3A3F51),
    onSecondaryFixedVariant = Color(0xFF565B6F),
    tertiaryFixed = Color(0xFFEDCFFF),
    tertiaryFixedDim = Color(0xFFDEC2F0),
    onTertiaryFixed = Color(0xFF463157),
    onTertiaryFixedVariant = Color(0xFF644D75),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFFBBC5EE),
    onPrimary = Color(0xFF353F61),
    primaryContainer = Color(0xFF475174),
    onPrimaryContainer = Color(0xFFDCE2FF),
    inversePrimary = Color(0xFF545E82),
    secondary = Color(0xFFC1C5DD),
    onSecondary = Color(0xFF3B3F52),
    secondaryContainer = Color(0xFF363B4D),
    onSecondaryContainer = Color(0xFFBABED5),
    tertiary = Color(0xFFF5E1FF),
    onTertiary = Color(0xFF634C74),
    tertiaryContainer = Color(0xFFEDCFFF),
    onTertiaryContainer = Color(0xFF5A446B),
    background = Color(0xFF0D0E12),
    onBackground = Color(0xFFE5E4F0),
    surface = Color(0xFF0D0E12),
    onSurface = Color(0xFFE5E4F0),
    surfaceVariant = Color(0xFF24252E),
    onSurfaceVariant = Color(0xFFAAAAB5),
    surfaceTint = Color(0xFFBBC5EE),
    inverseSurface = Color(0xFFFAF8FE),
    inverseOnSurface = Color(0xFF54555A),
    error = Color(0xFFF97386),
    onError = Color(0xFF490013),
    errorContainer = Color(0xFF871C34),
    onErrorContainer = Color(0xFFFF97A3),
    outline = Color(0xFF74757F),
    outlineVariant = Color(0xFF464750),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF2A2C34),
    surfaceDim = Color(0xFF0D0E12),
    surfaceContainer = Color(0xFF181920),
    surfaceContainerHigh = Color(0xFF1E1F26),
    surfaceContainerHighest = Color(0xFF24252E),
    surfaceContainerLow = Color(0xFF121318),
    surfaceContainerLowest = Color(0xFF000000),
    primaryFixed = Color(0xFFC9D3FD),
    primaryFixedDim = Color(0xFFBBC5EE),
    onPrimaryFixed = Color(0xFF2B3556),
    onPrimaryFixedVariant = Color(0xFF475174),
    secondaryFixed = Color(0xFFDDE1F9),
    secondaryFixedDim = Color(0xFFCFD3EB),
    onSecondaryFixed = Color(0xFF3A3F51),
    onSecondaryFixedVariant = Color(0xFF565B6F),
    tertiaryFixed = Color(0xFFEDCFFF),
    tertiaryFixedDim = Color(0xFFDEC2F0),
    onTertiaryFixed = Color(0xFF463157),
    onTertiaryFixedVariant = Color(0xFF644D75),
)
